CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Customers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" text NOT NULL,
    "MiddleNames" text NULL,
    "Surname" text NOT NULL,
    "EmailAddress" text NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Customers" PRIMARY KEY ("Id")
);

CREATE TABLE "Product" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Price" numeric NOT NULL,
    CONSTRAINT "PK_Product" PRIMARY KEY ("Id")
);

CREATE TABLE "Addresses" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CustomerId" integer NOT NULL,
    "Line1" text NOT NULL,
    "Line2" text NULL,
    "Line3" text NULL,
    "Town" text NOT NULL,
    "County" text NULL,
    "Country" text NOT NULL,
    "PostCode" text NOT NULL,
    CONSTRAINT "PK_Addresses" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Addresses_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Orders" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CustomerId" integer NOT NULL,
    "DeliveryAddressId" integer NOT NULL,
    "Total" numeric NOT NULL,
    CONSTRAINT "PK_Orders" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Orders_Addresses_DeliveryAddressId" FOREIGN KEY ("DeliveryAddressId") REFERENCES "Addresses" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Orders_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "OrderProduct" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrderId" integer NOT NULL,
    "ProductId" integer NOT NULL,
    "Quantity" integer NOT NULL,
    CONSTRAINT "PK_OrderProduct" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrderProduct_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_OrderProduct_Product_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Product" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Addresses_CustomerId" ON "Addresses" ("CustomerId");

CREATE INDEX "IX_OrderProduct_OrderId" ON "OrderProduct" ("OrderId");

CREATE INDEX "IX_OrderProduct_ProductId" ON "OrderProduct" ("ProductId");

CREATE INDEX "IX_Orders_CustomerId" ON "Orders" ("CustomerId");

CREATE INDEX "IX_Orders_DeliveryAddressId" ON "Orders" ("DeliveryAddressId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230325165107_InitialCreate', '6.0.4');

COMMIT;
