version: "3.3"

services:
  web-prod:
    image: "jamerst/o-data-grid.api:latest"
    ports:
      - "80:5000"
    depends_on:
      - db
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      TZ: "Europe/London"
      CultureName: "en-GB"
    networks:
      - o-data-grid.api
    restart: always
  db:
    image: "postgres:14.2"
    environment:
        POSTGRES_DB: o-data-grid-demo_db
        POSTGRES_USER: o-data-grid
        POSTGRES_PASSWORD: o-data-grid
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-data/initdb.d:/docker-entrypoint-initdb.d/
    networks:
      - o-data-grid.api
    restart: always

volumes:
  postgres-data:

networks:
  o-data-grid-demo:
    driver: bridge