version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - db
    volumes:
      - ./:/app:Z
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro,Z
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: "Europe/London"
      CultureName: "en-GB"
    networks:
      - o-data-grid-demo
  db:
    image: "postgres:14.2"
    environment:
        POSTGRES_DB: o-data-grid-demo_db
        POSTGRES_USER: o-data-grid
        POSTGRES_PASSWORD: o-data-grid
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-data/initdb.d:/docker-entrypoint-initdb.d/:Z
    networks:
      - o-data-grid-demo

volumes:
  postgres-data:

networks:
  o-data-grid-demo:
    driver: bridge