FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app

# install Visual Studio debugger
RUN curl -sSL https://aka.ms/getvsdbgsh | /bin/sh /dev/stdin -v latest -l /vsdbg

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

ENTRYPOINT dotnet watch run --urls=https://+:5000